version: "3"
services:
  auth_service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - 4000:5000
    volumes:
      - ./auth-service:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MYSQL_ROOT_PASSWORD=18120113
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_INITDB_COLLATION=utf8mb4_unicode_ci
      - MYSQL_ROOT_PASSWORD=18120113
      - MYSQL_DATABASE=crowdsourcing-tool
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=18120113
    depends_on:
      - db
