version: "3"
services:
  auth_service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - 4000:5000
    volumes:
      - ./auth-service:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - ncdai_network
    depends_on:
      - db_service

  core_service:
    build:
      context: ./core-service
      dockerfile: Dockerfile
    ports:
      - 4400:5000
    volumes:
      - ./core-service:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - ncdai_network
    depends_on:
      - db_service

  db_service:
    image: mysql:8.0
    environment:
      - MYSQL_INITDB_COLLATION=utf8mb4_unicode_ci
      - MYSQL_ROOT_PASSWORD=18120113
      - MYSQL_DATABASE=crowdsourcing_tool
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - ncdai_network

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db_service
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=18120113
    networks:
      - ncdai_network
    depends_on:
      - db_service

  nginx:
    image: nginx:1.25.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    networks:
      - ncdai_network
    depends_on:
      - auth_service
      - core_service

networks:
  ncdai_network: